### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Rastopyr** [Rastopyr/github-insights#1]
- [ ] Github API Layer
  - [ ] Pagination
  - [ ] Create correct queries for endpoints(not like ember-data-github)
- [ ] Clean lint
  - [ ] Templates
  - [ ] Javascript
- [ ] CI/CD
  - [ ] Tests
  - [ ] Build
  - [ ] Deliver
- [ ] Components
  - [ ] Logout
  - [ ] Activity
    - [x] By repository
    - [ ] By date
    - [ ] By organization
    - [ ] By user(gh-streak)
  - [ ] Events
    - [ ] PullRequests
      - [x] Headline
      - [ ] Repositories
    - [ ] Commits
      - [x] Headline
      - [ ] Repositories
- [ ] Serverless
  - [ ] GithubObtainAccessToken lambda
